### ISSUE TITLE
Manual package

### ISSUE THREAD

**Issue by rafaelfrc** [adityadua24/robopy#10]
Is the intention here to create a version of that manual (Robotics For MATLAB Release X Toolbox) used in the MATLAB version?

**Comment by petercorke** [comment]
Are you referring to the PDF manual that ships with the Robotics Toolbox for MATLAB?

**Comment by rafaelfrc** [comment]
Yes, as a Python version. I intend to start writing the Robopy documentation and I do not know which model to adopt.

**Comment by adityadua24** [comment]
The model i had on mind was:-
- Add doc strings in code
- Use sphinx to extract it
- Publish it within the robopy's website, using the theme: https://github.com/rtfd/sphinx_rtd_theme#read-the-docs-sphinx-theme

**Comment by rafaelfrc** [comment]
Okay, that's a good idea. I'll read how to do and apply.

**Comment by petercorke** [comment]
The doc strings could be cut and pasted from the MATLAB code, but with adjustments made for:

- change of call syntax and argument handling due to python vs MATLAB
- my MATLAB comments use a very subtle markup language which is:

> Inspired by pydoc format, this allows simple markup in a Matlab function's
> text style documentation block.
> 
> This is a heading::
> 
> any line starting with a capital and ending with a :: becomes a section heading.
> 
> Lists:
> 
> - any series of lines starting with a dash is a bullet point
>    - and this is a sub list of bullet points
>    - really long lines should be formatted like this
>      and have the same level of text indent to be considered as
>      part of the same dot point
> 
> These result in lists created with <ul> and </ul> tags.
> 
> Tables:
> 
>   key   description of key
>   key2  description of key2, which might be a very long description
>         in which case we continue it on a new line that has the same
>         level of indent as the line above.
> 
> The key can contain any sequence of characters but no more than a single consecutive
> space.  The gap between key and description must be at three or more spaces.
> 
> Paragraphs:
> 
> All other text is considered to be a paragraph, and consecutive lines are
> joined into a block of text text displayed between <p> and </p> tags.
> 
> An attempt is made to parse out what looks like a Matlab function definition
> from the start of the paragraph from which variables names are found.  These
> are all converted to bold text in the rest of the paragraph.  They are generally
> converted to lower case unless:
>     * the are in the nocaps list: R, T, J and certain other symbols
>     * it is already in camel case 
> 
> Preformatted text, ie. code, is set by inserting 8 or more leading spaces.
> 
> Peter Corke, May 2011
