### ISSUE TITLE
ctraj assert error

### ISSUE THREAD

**Issue by sondre1988** [adityadua24/robopy#12]
Hi,

I just downloaded the library and i wanted to test the "ctraj" funcion. However, i got the following assert error:

C:\Anaconda3\lib\site-packages\robopy\base\util.py in ctraj(T0, T1, N)
      5     from .transforms import transl
      6     assert type(N) is float or type(N) is int
----> 7     assert type(T0) is list or ishomog(T0, 4)
      8     assert type(T1) is list or ishomog(T1, 4)
      9

C:\Anaconda3\lib\site-packages\robopy\base\common.py in ishomog(tr, dim, rtest)
     14     See Also: isrot, ishomog2, isvec"""
     15     assert type(tr) is np.matrix, "Argument should be a numpy matrix"
---> 16     assert dim == (3, 3) or dim == (4, 4)
     17     is_valid = None
     18     if rtest == 'valid':

After modifying all function calls of "ishomog(T0, 4)" to "ishomog(T0, (4, 4))" it works.

In addition to this error i noticed that an error occurs when running the following:
```python
import robopy.base as base
from robopy.base.util import ctraj
import numpy as np

# Poses
T0 = base.transforms.transl([1, 2, 3])
T1 = base.transforms.transl([2, 3, 4])

# Ctraj Test
traj = base.util.ctraj(T0, T1, 100)`
```
The resulting error is caused bu zero division and the error message is:
C:\Anaconda3\lib\site-packages\robopy\base\util.py in one_to_one(T0, T1)
     24         rot_traj = []
     25         for i in range(1, N+1):
---> 26             rot_traj.append(q0.interp(q1, 1/N * i).to_rot())
     27         return rot_traj
     28

C:\Anaconda3\lib\site-packages\robopy\base\quaternion.py in interp(self, qr, r, shortest)
    355         theta = theta_0 * r  # theta = angle between v0 and result
    356         s1 = float(math.cos(theta) - dot * math.sin(theta) / math.sin(theta_0))
--> 357         s2 = math.sin(theta) / math.sin(theta_0)
    358         out = (q1 * s1) + (q2 * s2)
    359         return UnitQuaternion(s=float(out[0, 0]), v=out[0, 1:])

**Comment by adityadua24** [comment]
Just update your package, I have fixed these issues.

**Comment by sondre1988** [comment]
Thanks for the updated version of the robopy package! I have tested the ctraj function and it works very vell in my robotics application :-D
