### ISSUE TITLE
Too bad documentation and validation of all functions.

### ISSUE THREAD

**Issue by Nikronic** [adityadua24/robopy#26]
I have tried many functions and they simply made hard everything.
for example:
```python

import robopy.base.transforms as transforms
transforms.eul2r(phi=deg, theta=deg, psi=deg,unit='deg')
```
But it won't work. Because your degree should be a matrix of numpy with shape `[1,1]`. And it is not rational and documentation is not providing any information about this.

**Comment by hkk0x26** [comment]
Try this

` 
import robopy.base.transforms as transforms
XYZSeq = np.matrix([np.degrees(90),np.degrees(0),np.degrees(0)])
transforms.eul2r(XYZSeq,unit='deg')
`

**Comment by hkk0x26** [comment]
Try this

```python
import robopy.base.transforms as transforms
import numpy as np

XYZSeq = np.matrix([np.degrees(90),np.degrees(0),np.degrees(0)])

transforms.eul2r(XYZSeq,unit='deg')

```
